// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Oracle Team",
            "url": "https://github.com/orgs/xxxx/projects/1",
            "email": "oracle.team@mail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/members/{id}": {
            "get": {
                "description": "GetMemberById handles request for Get Member by Id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Member"
                ],
                "summary": "Get Member by Id",
                "parameters": [
                    {
                        "type": "string",
                        "default": "id",
                        "description": "accept language",
                        "name": "Accept-Language",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "id of Member",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Response",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/oracle_com_oracle_my-go-oracle-app_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/oracle_com_oracle_my-go-oracle-app_service_member.MemberResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "InternalServerError"
                    }
                }
            }
        }
    },
    "definitions": {
        "oracle_com_oracle_my-go-oracle-app_pkg_response.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "application error code for tracing",
                    "type": "integer",
                    "example": 0
                },
                "msg": {
                    "description": "error message",
                    "type": "string",
                    "example": " "
                },
                "status": {
                    "description": "true if we have error",
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "oracle_com_oracle_my-go-oracle-app_pkg_response.Response": {
            "type": "object",
            "properties": {
                "code": {},
                "data": {},
                "error": {
                    "$ref": "#/definitions/oracle_com_oracle_my-go-oracle-app_pkg_response.Error"
                },
                "message": {
                    "type": "string"
                },
                "pagination": {},
                "serverTime": {
                    "type": "integer"
                }
            }
        },
        "oracle_com_oracle_my-go-oracle-app_service_member.MemberResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "info": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "/my-go-oracle-app",
	Schemes:          []string{},
	Title:            "MY GO ORACLE APP API",
	Description:      "This service is to handle My Go ORACLE App. For more detail, please visit https://github.com/",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
