// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Oracle Team",
            "url": "https://github.com/orgs/xxxx/projects/1",
            "email": "oracle.team@mail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/members/": {
            "get": {
                "description": "GetAllMembers handles request for Get Members",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Member"
                ],
                "summary": "Get All  by Id",
                "parameters": [
                    {
                        "type": "string",
                        "default": "id",
                        "description": "accept language",
                        "name": "Accept-Language",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "limit data",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page data",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "name filter",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "address filter",
                        "name": "address",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ageStart filter",
                        "name": "ageStart",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ageEnd filter",
                        "name": "ageEnd",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "salaryStart filter",
                        "name": "salaryStart",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "salaryEnd filter",
                        "name": "salaryEnd",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "category filter",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "level filter",
                        "name": "level",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "orderBy order by",
                        "name": "orderBy",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "orderType asc/desc",
                        "name": "orderType",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Response",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/oracle_com_oracle_my-go-oracle-app_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/oracle_com_oracle_my-go-oracle-app_service_member.MemberResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "InternalServerError"
                    }
                }
            },
            "post": {
                "description": "CreateMember handles request for creating a new member",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Member"
                ],
                "summary": "Create Member",
                "parameters": [
                    {
                        "type": "string",
                        "default": "id",
                        "description": "accept language",
                        "name": "Accept-Language",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Member Request Body",
                        "name": "member",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/oracle_com_oracle_my-go-oracle-app_service_member.MemberRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Response",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/oracle_com_oracle_my-go-oracle-app_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/oracle_com_oracle_my-go-oracle-app_service_member.MemberResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "InternalServerError"
                    }
                }
            }
        },
        "/members/{id}": {
            "get": {
                "description": "GetMemberById handles request for Get Member by Id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Member"
                ],
                "summary": "Get Member by Id",
                "parameters": [
                    {
                        "type": "string",
                        "default": "id",
                        "description": "accept language",
                        "name": "Accept-Language",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "id of Member",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Response",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/oracle_com_oracle_my-go-oracle-app_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/oracle_com_oracle_my-go-oracle-app_service_member.MemberResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "InternalServerError"
                    }
                }
            },
            "put": {
                "description": "UpdateMember handles request for updating a member",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Member"
                ],
                "summary": "Update Member",
                "parameters": [
                    {
                        "type": "string",
                        "default": "id",
                        "description": "accept language",
                        "name": "Accept-Language",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "id of Member",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Member Request Body",
                        "name": "member",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/oracle_com_oracle_my-go-oracle-app_service_member.MemberRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Response",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/oracle_com_oracle_my-go-oracle-app_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/oracle_com_oracle_my-go-oracle-app_service_member.MemberResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "InternalServerError"
                    }
                }
            },
            "delete": {
                "description": "DeleteMember handles request for deleting a member",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Member"
                ],
                "summary": "Delete Member",
                "parameters": [
                    {
                        "type": "string",
                        "default": "id",
                        "description": "accept language",
                        "name": "Accept-Language",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "id of Member",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Response",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/oracle_com_oracle_my-go-oracle-app_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "InternalServerError"
                    }
                }
            }
        }
    },
    "definitions": {
        "oracle_com_oracle_my-go-oracle-app_pkg_response.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "application error code for tracing",
                    "type": "integer",
                    "example": 0
                },
                "msg": {
                    "description": "error message",
                    "type": "string",
                    "example": " "
                },
                "status": {
                    "description": "true if we have error",
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "oracle_com_oracle_my-go-oracle-app_pkg_response.Response": {
            "type": "object",
            "properties": {
                "code": {},
                "data": {},
                "error": {
                    "$ref": "#/definitions/oracle_com_oracle_my-go-oracle-app_pkg_response.Error"
                },
                "message": {
                    "type": "string"
                },
                "pagination": {},
                "serverTime": {
                    "type": "integer"
                }
            }
        },
        "oracle_com_oracle_my-go-oracle-app_service_member.Address": {
            "type": "object",
            "properties": {
                "primary": {
                    "type": "string"
                },
                "secondary": {
                    "type": "string"
                }
            }
        },
        "oracle_com_oracle_my-go-oracle-app_service_member.MemberDetail": {
            "type": "object",
            "properties": {
                "member_id": {
                    "type": "string"
                },
                "onboarding_stage": {
                    "type": "string"
                },
                "risk_rating": {
                    "type": "string"
                }
            }
        },
        "oracle_com_oracle_my-go-oracle-app_service_member.MemberInfo": {
            "type": "object",
            "properties": {
                "address": {
                    "$ref": "#/definitions/oracle_com_oracle_my-go-oracle-app_service_member.Address"
                },
                "age": {
                    "type": "integer"
                },
                "salary": {
                    "type": "integer"
                }
            }
        },
        "oracle_com_oracle_my-go-oracle-app_service_member.MemberRequest": {
            "type": "object",
            "properties": {
                "createdDate": {
                    "type": "string"
                },
                "detail": {
                    "$ref": "#/definitions/oracle_com_oracle_my-go-oracle-app_service_member.MemberDetail"
                },
                "id": {
                    "type": "integer",
                    "example": 12345
                },
                "info": {
                    "$ref": "#/definitions/oracle_com_oracle_my-go-oracle-app_service_member.MemberInfo"
                },
                "isDeleted": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "policy": {
                    "$ref": "#/definitions/oracle_com_oracle_my-go-oracle-app_service_member.Policy"
                },
                "updatedDate": {
                    "$ref": "#/definitions/sql.NullTime"
                }
            }
        },
        "oracle_com_oracle_my-go-oracle-app_service_member.MemberResponse": {
            "type": "object",
            "properties": {
                "created_date": {
                    "type": "string"
                },
                "detail": {
                    "$ref": "#/definitions/oracle_com_oracle_my-go-oracle-app_service_member.MemberDetail"
                },
                "id": {
                    "type": "integer"
                },
                "info": {
                    "$ref": "#/definitions/oracle_com_oracle_my-go-oracle-app_service_member.MemberInfo"
                },
                "is_deleted": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "policy": {
                    "$ref": "#/definitions/oracle_com_oracle_my-go-oracle-app_service_member.Policy"
                }
            }
        },
        "oracle_com_oracle_my-go-oracle-app_service_member.Policy": {
            "type": "object",
            "properties": {
                "data_categories": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "effective_date": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "sql.NullTime": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "/my-go-oracle-app",
	Schemes:          []string{},
	Title:            "MY GO ORACLE APP API",
	Description:      "This service is to handle My Go ORACLE App. For more detail, please visit https://github.com/",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
